### ISSUE TITLE
readable-stream version

### ISSUE THREAD

**Issue by Klowner** [jpommerening/node-lazystream#2]
Hi, just curious if you'd be open to changing dependency to any version of `readable-stream` and bump to `1.0`? This library does a fantastic job of fixing an issue in vinyl-fs and would definitely like to incorporate it.

Cheers!

-Mark

**Comment by phated** [comment]
To clarify, this module attempts to use the built in `stream` module before attempting to use `readable-stream` but I think it would be a better idea to always you `readable-stream` directly (not any version, just latest).  See https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by phated** [comment]
The above issues are being brought up because we'd like to use this module in the next version of gulp.

**Comment by jpommerening** [comment]
Sounds like a pretty good idea. I noticed the ancient version a few weeks ago but didn't bother to do anything about it ("If it ain't broke…").

Oh, and sorry about the delay. Family time ;)

Looking back at the conditional `require('readable-stream')` I absolutely agree that it's not a good idea now that we have 3 different major streams APIs.

**Comment by jpommerening** [comment]
@Klowner can you try `lazystream@1.0.0-rc1` and tell me if that'll do?

**Comment by Klowner** [comment]
@jpommerening works perfectly here! Everything look good to you, @phated ?

**Comment by phated** [comment]
Yep. LGTM

**Comment by jpommerening** [comment]
Ok, published as `1.0.0`. Thanks, guys!

**Comment by Klowner** [comment]
Thank you! :+1:
